server:
  port: 9001

spring:
  application:
    name: RESOURCE-SERVICE
  mvc:
    static-path-pattern: /resources/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
