server:
  port: 9000

spring:
  application:
    name: WS-SERVICE
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  mvc:
    static-path-pattern: /resources/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true